"""
carl_scout_bc.py — Behavioral Cloning Trainer for CARL Primate Scout Arms.

Phase 2b of CARL v5 Master Roadmap.

Trains a PyTorch LTC (Liquid Time-Constant) neural network to imitate
the IK demonstrations generated by carl_scout_ik_demo.py (Phase 2a).

Pipeline:
  1. Load demonstration data from memory/scout_demos.npz
  2. Train PyTorch LTC network (51D -> 48H -> 16D) via MSE + Adam
  3. Export trained weights to memory/scout_bc_weights.npz (numpy-compatible)
  4. Evaluate: run 20 episodes with BC weights, report avg distance

Usage:
  python carl_scout_bc.py --epochs 200 --lr 1e-3
  python carl_scout_bc.py --eval-only             # just evaluate saved weights
"""

import os
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import mujoco

from carl_body_interface import (
    BodyInterface, MODEL_PATH, ARM_CTRL_LOW, ARM_CTRL_HIGH, ARMS_CTRL,
)
from carl_scout_ik_demo import get_scout_state, spawn_target

# ─── Constants ────────────────────────────────────────────────────────────────
STATE_DIM  = 51
ACTION_DIM = 16
HIDDEN_DIM = 48
DEMO_PATH  = "memory/scout_demos.npz"
BC_WEIGHTS = "memory/scout_bc_weights.npz"


# ═══════════════════════════════════════════════════════════════════════════════
# PyTorch LTC Network (mirrors numpy ScoutArmPolicy exactly)
# ═══════════════════════════════════════════════════════════════════════════════

class LTCPolicyTorch(nn.Module):
    """
    Liquid Time-Constant recurrent network in PyTorch.
    Architecture matches ScoutArmPolicy from carl_scout_train.py:
      - Input projection: W_in (H x S), Tau_in (H x S)
      - Recurrent: W_rec (H x H), Tau_rec (H x H)
      - Output: W_out (A x H)
      - Adaptive time-constant: tau = exp(tanh(Tau_in @ s + Tau_rec @ x + tau_b))
      - State update: x += (dt/tau) * (-x + tanh(W_in @ s + W_rec @ x + b))
      - Output: tanh(W_out @ x + b_out)
    """

    def __init__(self, state_dim=STATE_DIM, action_dim=ACTION_DIM, hidden_dim=HIDDEN_DIM):
        super().__init__()
        self.hidden_dim = hidden_dim

        # Input projection
        self.W_in  = nn.Parameter(torch.randn(hidden_dim, state_dim) * 0.08)
        self.W_rec = nn.Parameter(torch.randn(hidden_dim, hidden_dim) * 0.08)
        self.b     = nn.Parameter(torch.zeros(hidden_dim))

        # Time-constant modulation
        self.Tau_in  = nn.Parameter(torch.randn(hidden_dim, state_dim) * 0.08)
        self.Tau_rec = nn.Parameter(torch.randn(hidden_dim, hidden_dim) * 0.08)
        self.tau_b   = nn.Parameter(torch.ones(hidden_dim) * 1.5)

        # Output projection
        self.W_out = nn.Parameter(torch.randn(action_dim, hidden_dim) * 0.08)
        self.b_out = nn.Parameter(torch.zeros(action_dim))

    def forward(self, states_seq, dt=0.005):
        """
        Forward pass over a sequence.
        states_seq: (batch, time, state_dim)
        Returns: (batch, time, action_dim)
        """
        B, T, _ = states_seq.shape
        device = states_seq.device

        x = torch.zeros(B, self.hidden_dim, device=device)
        outputs = []

        for t in range(T):
            s = states_seq[:, t, :]  # (B, S)

            # Adaptive time-constant
            tau_mod = torch.tanh(s @ self.Tau_in.t() + x @ self.Tau_rec.t() + self.tau_b)
            tau = torch.exp(tau_mod)

            # State update
            dx = -x + torch.tanh(s @ self.W_in.t() + x @ self.W_rec.t() + self.b)
            x = x + (dt / tau) * dx

            # Output
            out = torch.tanh(x @ self.W_out.t() + self.b_out)
            outputs.append(out)

        return torch.stack(outputs, dim=1)  # (B, T, A)

    def forward_single(self, state, x_hidden, dt=0.005):
        """
        Single-step forward (for inference loop).
        state: (state_dim,) or (1, state_dim)
        x_hidden: (hidden_dim,)
        Returns: action (action_dim,), new_hidden (hidden_dim,)
        """
        s = state.unsqueeze(0) if state.dim() == 1 else state
        x = x_hidden.unsqueeze(0) if x_hidden.dim() == 1 else x_hidden

        tau_mod = torch.tanh(s @ self.Tau_in.t() + x @ self.Tau_rec.t() + self.tau_b)
        tau = torch.exp(tau_mod)
        dx = -x + torch.tanh(s @ self.W_in.t() + x @ self.W_rec.t() + self.b)
        x = x + (dt / tau) * dx
        out = torch.tanh(x @ self.W_out.t() + self.b_out)

        return out.squeeze(0), x.squeeze(0)


# ═══════════════════════════════════════════════════════════════════════════════
# Dataset
# ═══════════════════════════════════════════════════════════════════════════════

class DemoDataset(Dataset):
    """Loads IK demonstrations for training."""

    def __init__(self, path=DEMO_PATH, seq_len=50):
        data = np.load(path, allow_pickle=True)
        self.states  = data['states']   # (N, T, 51)
        self.actions = data['actions']  # (N, T, 16)
        self.lengths = data['lengths']  # (N,)
        self.seq_len = seq_len

        # Create sub-sequences for efficient training
        self.sequences = []
        for ep in range(len(self.states)):
            T = int(self.lengths[ep])
            for start in range(0, T - seq_len, seq_len // 2):
                self.sequences.append((ep, start, start + seq_len))

        print(f"  [DATA] Loaded {len(self.states)} episodes, "
              f"created {len(self.sequences)} training sub-sequences (len={seq_len})")

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        ep, start, end = self.sequences[idx]
        states  = torch.tensor(self.states[ep, start:end], dtype=torch.float32)
        actions = torch.tensor(self.actions[ep, start:end], dtype=torch.float32)
        return states, actions


# ═══════════════════════════════════════════════════════════════════════════════
# Weight Export/Import (PyTorch <-> Numpy)
# ═══════════════════════════════════════════════════════════════════════════════

def export_weights_to_numpy(net, path=BC_WEIGHTS, quiet=False):
    """Export PyTorch LTC weights to numpy format compatible with ScoutArmPolicy."""
    np.savez(path,
        W_in=net.W_in.detach().cpu().numpy(),
        W_rec=net.W_rec.detach().cpu().numpy(),
        b=net.b.detach().cpu().numpy(),
        Tau_in=net.Tau_in.detach().cpu().numpy(),
        Tau_rec=net.Tau_rec.detach().cpu().numpy(),
        tau_b=net.tau_b.detach().cpu().numpy(),
        W_out=net.W_out.detach().cpu().numpy(),
        b_out=net.b_out.detach().cpu().numpy(),
    )
    if not quiet:
        print(f"  [EXPORT] Weights saved to {path}")


def import_weights_from_numpy(net, path=BC_WEIGHTS):
    """Load numpy weights into PyTorch LTC network."""
    data = np.load(path)
    with torch.no_grad():
        net.W_in.copy_(torch.tensor(data['W_in']))
        net.W_rec.copy_(torch.tensor(data['W_rec']))
        net.b.copy_(torch.tensor(data['b']))
        net.Tau_in.copy_(torch.tensor(data['Tau_in']))
        net.Tau_rec.copy_(torch.tensor(data['Tau_rec']))
        net.tau_b.copy_(torch.tensor(data['tau_b']))
        net.W_out.copy_(torch.tensor(data['W_out']))
        net.b_out.copy_(torch.tensor(data['b_out']))
    print(f"  [IMPORT] Weights loaded from {path}")


class NumpyLTCPolicy:
    """
    Numpy-only LTC policy for fast inference (no PyTorch dependency).
    Drop-in replacement for ScoutArmPolicy from carl_scout_train.py.
    """

    def __init__(self, path=BC_WEIGHTS):
        data = np.load(path)
        self.W_in    = data['W_in']
        self.W_rec   = data['W_rec']
        self.b       = data['b']
        self.Tau_in  = data['Tau_in']
        self.Tau_rec = data['Tau_rec']
        self.tau_b   = data['tau_b']
        self.W_out   = data['W_out']
        self.b_out   = data['b_out']
        self.x = np.zeros(self.W_in.shape[0])

    def reset(self):
        self.x.fill(0.0)

    def forward(self, s, dt=0.005):
        tau_mod = np.tanh(self.Tau_in @ s + self.Tau_rec @ self.x + self.tau_b)
        tau = np.exp(tau_mod)
        dx = -self.x + np.tanh(self.W_in @ s + self.W_rec @ self.x + self.b)
        self.x = self.x + (dt / tau) * dx
        return np.tanh(self.W_out @ self.x + self.b_out)


# ═══════════════════════════════════════════════════════════════════════════════
# Training
# ═══════════════════════════════════════════════════════════════════════════════

def train_bc(epochs=200, lr=1e-3, batch_size=64, seq_len=50):
    """Train LTC network via behavioral cloning on IK demonstrations."""

    print("=" * 65)
    print("  CARL Primate Scout -- Behavioral Cloning Trainer")
    print(f"  Epochs: {epochs} | LR: {lr} | Batch: {batch_size} | Seq: {seq_len}")
    print("=" * 65)

    # Load dataset
    dataset = DemoDataset(DEMO_PATH, seq_len=seq_len)
    loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True)

    # Create network
    net = LTCPolicyTorch()
    optimizer = optim.Adam(net.parameters(), lr=lr, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    loss_fn = nn.MSELoss()

    total_params = sum(p.numel() for p in net.parameters())
    print(f"  [NET] LTC Policy: {total_params} parameters")
    print(f"  [NET] Architecture: {STATE_DIM}D -> {HIDDEN_DIM}H -> {ACTION_DIM}D")

    best_loss = float('inf')

    for epoch in range(epochs):
        net.train()
        epoch_loss = 0.0
        n_batches = 0

        for states_batch, actions_batch in loader:
            # Forward through full sequence
            pred_actions = net(states_batch)

            loss = loss_fn(pred_actions, actions_batch)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(net.parameters(), 1.0)
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

        scheduler.step()
        avg_loss = epoch_loss / max(n_batches, 1)

        if avg_loss < best_loss:
            best_loss = avg_loss
            export_weights_to_numpy(net, BC_WEIGHTS, quiet=True)
            saved_this_epoch = True
        else:
            saved_this_epoch = False

        if (epoch + 1) % 10 == 0 or epoch == 0:
            marker = " [saved]" if saved_this_epoch else ""
            print(f"  Epoch {epoch+1:4d}/{epochs} | Loss: {avg_loss:.6f} | "
                  f"Best: {best_loss:.6f} | LR: {scheduler.get_last_lr()[0]:.6f}{marker}")

    print(f"\n  [DONE] Best MSE loss: {best_loss:.6f}")
    print(f"  [DONE] Weights: {BC_WEIGHTS}")
    return net


# ═══════════════════════════════════════════════════════════════════════════════
# Evaluation
# ═══════════════════════════════════════════════════════════════════════════════

def evaluate_bc(n_episodes=20, max_steps=200, render=False):
    """Evaluate BC-trained policy in simulation."""

    print("=" * 65)
    print("  CARL Primate Scout -- BC Policy Evaluation")
    print(f"  Episodes: {n_episodes} | Steps: {max_steps}")
    print("=" * 65)

    # Load trained policy
    policy = NumpyLTCPolicy(BC_WEIGHTS)
    print(f"  [LOAD] Loaded weights from {BC_WEIGHTS}")

    model = mujoco.MjModel.from_xml_path(MODEL_PATH)
    data = mujoco.MjData(model)
    body = BodyInterface(model)
    rng = np.random.default_rng(seed=99)

    viewer = None
    if render:
        from mujoco import viewer as mj_viewer
        viewer = mj_viewer.launch_passive(model, data)

    center = (ARM_CTRL_HIGH + ARM_CTRL_LOW) / 2.0
    scale  = (ARM_CTRL_HIGH - ARM_CTRL_LOW) / 2.0 + 1e-8

    modes = ['left', 'right', 'both']
    all_dist_L, all_dist_R = [], []

    for ep in range(n_episodes):
        mode = modes[ep % 3]
        policy.reset()

        mujoco.mj_resetData(model, data)
        mujoco.mj_forward(model, data)

        target_L = spawn_target(rng, 'L')
        target_R = spawn_target(rng, 'R')

        # Place cubes at targets
        if len(body.obj_body_ids) >= 2:
            cube0_jnt = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "fj_cube_0")
            q0 = model.jnt_qposadr[cube0_jnt]
            data.qpos[q0:q0+3] = target_L
            data.qpos[q0+3:q0+7] = [1, 0, 0, 0]
            cube1_jnt = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "fj_cube_1")
            q1 = model.jnt_qposadr[cube1_jnt]
            data.qpos[q1:q1+3] = target_R
            data.qpos[q1+3:q1+7] = [1, 0, 0, 0]
        mujoco.mj_forward(model, data)

        for step in range(max_steps):
            body.lock_base(data)
            state = get_scout_state(body, data, target_L, target_R, mode)
            action_norm = policy.forward(state)
            action_raw = action_norm * scale + center
            action_raw = np.clip(action_raw, ARM_CTRL_LOW, ARM_CTRL_HIGH)
            data.ctrl[ARMS_CTRL] = action_raw

            for _ in range(10):
                mujoco.mj_step(model, data)

            if viewer and viewer.is_running():
                viewer.sync()

        dist_L = np.linalg.norm(target_L - body.get_fingertip_mean_pos(data, 'L'))
        dist_R = np.linalg.norm(target_R - body.get_fingertip_mean_pos(data, 'R'))
        all_dist_L.append(dist_L)
        all_dist_R.append(dist_R)

        print(f"  Ep {ep+1:3d}/{n_episodes} | {mode:6s} | "
              f"Dist_L: {dist_L:.4f}m | Dist_R: {dist_R:.4f}m")

    if viewer:
        viewer.close()

    avg_L = np.mean(all_dist_L)
    avg_R = np.mean(all_dist_R)
    print(f"\n{'=' * 65}")
    print(f"  Average Dist_L: {avg_L:.4f}m | Average Dist_R: {avg_R:.4f}m")
    success = avg_L < 0.08 and avg_R < 0.08
    print(f"  Status: {'PASS' if success else 'NEEDS MORE TRAINING'} (threshold: 0.08m)")
    print(f"{'=' * 65}")
    return avg_L, avg_R


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CARL Scout BC Trainer")
    parser.add_argument("--epochs", type=int, default=200, help="Training epochs")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size")
    parser.add_argument("--seq-len", type=int, default=50, help="Sequence length for TBPTT")
    parser.add_argument("--eval-only", action="store_true", help="Skip training, just evaluate")
    parser.add_argument("--render", action="store_true", help="Show viewer during eval")
    args = parser.parse_args()

    if not args.eval_only:
        train_bc(epochs=args.epochs, lr=args.lr,
                 batch_size=args.batch_size, seq_len=args.seq_len)

    evaluate_bc(n_episodes=20, max_steps=200, render=args.render)
